### ISSUE TITLE
Some Minor Changes

### ISSUE THREAD

**Issue by mohdomama** [RoboticsIIITH/roboticsiiith.github.io#11]
- Adithya and Bipasha are not officially part of RRC
- 1 ICRA in 2021, 2 ICRA in 2022

**Comment by TheProjectsGuy** [comment]
The project pages for some users are not redirecting properly. This could be because they are missing the `href` field in the compiled HTML.

![image](https://user-images.githubusercontent.com/29420733/178980948-9f488784-0c9a-4a6e-a12c-adef7f28de35.png)

If the link were working, the underlying HTML would look something like this

![image](https://user-images.githubusercontent.com/29420733/178981178-7a37a5a4-3152-442e-9cf0-2120e762bdd0.png)

**Comment by TheProjectsGuy** [comment]
This could be solved alongside #10

**Comment by mohdomama** [comment]
Solved. Closing.
